### ISSUE TITLE
傳送失敗...

### ISSUE THREAD

**Issue by wimotek** [we684123/Telegram_link_Line#13]
Line_TG_Bot, [2022-07-20 19:25]
傳送失敗...

原本欲傳送到TG的:
C42d01bc0b7e69fb8a6b7f02b6bb84c3b✅

處理失敗的資料：
{"type":"memberJoined","message_id":0,"userName":"","timestamp":1658316313376,"room_type":"group","room_id":"C42d01bc0b7e69fb8a6b7f02b6bb84c3b","joined":{"members":[{"type":"user","userId":"U883248f4e898d75d4633b0647f7795ab"}]}}

結果：
TypeError: Cannot read property 'line_user_data' of undefined

Line_TG_Bot, [2022-07-20 19:25]
bot發生錯誤，訊息如下:
Error: TypeError: Cannot read property 'line_user_data' of undefined

Line_TG_Bot, [2022-07-20 19:26]
你有新訊息!
來自：C42d01bc0b7e69fb8a6b7f02b6bb84c3b✅
點擊以快速切換至該房間 /d2

**Comment by we684123** [comment]
@wimotek 
那個... `memberLeft`的話，我還能理解
不過如果是 `memberJoined` 引發的，請問你有對TGbot下 `/up_version` 命令過嗎？
不論是第一次、或升級程式碼時，都要下這個指令喔

**Comment by wimotek** [comment]
有执行/ up_version. 



***@***.***
 
发件人： 永格天
发送时间： 2022-07-21 23:52
收件人： we684123/Telegram_link_Line
抄送： wimotek; Mention
主题： Re: [we684123/Telegram_link_Line] 傳送失敗... (Issue #13)
@wimotek
那個... memberLeft的話，我還能理解
不過如果是 memberJoined 引發的，請問你有對TGbot下 /up_version 命令過嗎？
不論是第一次、或升級程式碼時，都要下這個指令喔

**Comment by wjhuang3579** [comment]
踢掉bot，重新邀請加入 會不會就解決了？

**Comment by we684123** [comment]
你是剛使用的嗎？
如果是的話推薦直接重新把 [doc.gs](https://github.com/we684123/Telegram_link_Line/blob/master/Telegram_link_Line/doc.gs) 的內容貼上 doc，然後再下一次 `/up_version`
這樣應該可以解決。
