### ISSUE TITLE
無法設定LINE的webhook

### ISSUE THREAD

**Issue by eroalu4** [we684123/Telegram_link_Line#2]
貼網址後彈出這視窗
![chrome_2017-10-13_10-02-20](https://user-images.githubusercontent.com/25959158/31527259-89fe8afa-affe-11e7-8428-f6cda8da2c79.png)

**Comment by we684123** [comment]
ㄜ... 我應該是沒貼 LINE部分的網址沒錯
LINE webhook 的部分是要到自己bot後台改 
理論上沒有"網址"的問題

你是貼哪個網址啊?
