### ISSUE TITLE
請問是只能針對bot對話的才能回拋TG?

### ISSUE THREAD

**Issue by oliveryc** [we684123/Telegram_link_Line#3]
首先感謝您的分享，目前依照步驟都已經成功完成設定
並在line的bot中講話可以回傳到TG上
但除此之外其他的 個人對話/群組對話皆無法將訊息拋回TG
有其他辦法去對其他對話框進行抓資料拋送到TG嗎?

**Comment by we684123** [comment]
oliveryc 安安030//
想請問一下 你的意思是你單獨對Linebot說話，TG確實可以收到
但如果把Linebot邀進其他群組後，在其他群組發的內容 TGbot沒有收到對嗎?

如果是這樣可以先檢查一下 Sheet 的 log 分頁中是否有從 Linebot收到你發的訊息
如果沒收到有可能是設定上有問題，如果有收到請把你收到的那條訊息的log(C欄)內容
複製到 Debug 分頁中的 B2格
再去 Telegram_link_Line.gs 中，第7行 (var debug = 0;) 改成2
然後執行 doPost(e) 函式看看他噴出什麼"錯誤訊息"
如果有"錯誤訊息"的話還請po上來，這樣我才能猜測是什麼原因

或者你可以直接找我:D 
https://t.me/we684123

**Comment by oliveryc** [comment]
hi, 
單獨和linebot說話以及把Linebot邀進其他群組後 TGbot是都可以收到
是想問說如果不把linebot邀進群組,有辦法利用groupid之類資訊蒐集到資料拋到tgbot嗎?
雖然可能跟這隻程式原先目的不同XD不過還是想說問問看有沒有類似的方法?

thx

**Comment by we684123** [comment]
如果是這樣的話應該是不可能啦
這樣等於你直接在line的伺服器內撈資料了，而不是藉由line server吐資料給你
且這樣的話就沒有隱私可言了(有groupid就可以獲得資訊想想還滿可怕的)wwwww

**Comment by oliveryc** [comment]
也是~哈 感謝感謝
