### ISSUE TITLE
加入群後，發生 "您好!此群似乎還沒有與資料庫綁定，等主人綁定後我才能在此服務。" 問題，如何設定 ?

### ISSUE THREAD

**Issue by Zhubeibros** [we684123/Telegram_link_Line#7]
Hi,
將 bot 加入 TG Group 中，會跳出此 message
要如何再設定資料庫綁定才能排除些問題 ?

Zhubeibros

**Comment by we684123** [comment]
@Zhubeibros ㄟ都... 請問那個 **此訊息** 是什麼呢?
你好像沒有描述到? 能請你貼個截圖或描述一下嗎?

關於綁定TG群組一般來說
只要在bot那對房間下 "⭐️ 升級房間" 接下來照著綁定就可以了
![Imgur](https://imgur.com/JRb8BFZ.png)
![Imgur](https://imgur.com/Yi0yxrM.png)

請問這樣有解決你的問題嗎?

**Comment by Zhubeibros** [comment]
感謝您，後來解決了，是昇級房間後，要在群裡打上昇級房間的特定字串沒錯

Zhubeibros

永格天 ***@***.***> 於 2021年7月14日 週三 下午5:42寫道：
