### ISSUE TITLE
Line Bot 加入群後，從 TG 發過來的 message 有沒有機會可以直接從 Line Bot 直接就印出來

### ISSUE THREAD

**Issue by Zhubeibros** [we684123/Telegram_link_Line#8]
Hi,

主要是想實現在 TG 的 bot 收集到 TG Group chat 的訊息後，透過  Line Bot ，就能一直印出來
目前是卡在 Line Bot 在加入 LIne Group 後，是不會印訊息的

是我設定的問題嗎..

**Comment by we684123** [comment]
建議照著影片做，目前我確認程式沒有問題
https://www.youtube.com/watch?v=E-ofS-MiVzs
